### ISSUE TITLE
Backup and restore between Moodle instances 

### ISSUE THREAD

**Issue by AviMoto** [moodleou/moodle-filter_embedquestion#13]
When backup content with embededquestion filter from one site and restore in another the question will not load.
Optional solution:
Add secrete configuration to admin settings

**Comment by joyhaddad0** [comment]
Same here! When backuping from one version of Moodle to another (2 different servers), the embedded questions do not work.

I have to embed the questions from their respective restored categories all over again. Note that their link (IFrame) changes when I do so (this solution works, but it's not practical by any means).

**Comment by timhunt** [comment]
This is expected - and related to how this plugin implements security so that only teachers can embed questions.

We could have an admin option added, so you can add additional security secrets from other servers, which are accepted to validate embedding codes, but this is probably not a priority for us, so it will probably only happens if someone does a pull request.

**Comment by joyhaddad0** [comment]
Thank you for your prompt response!

Frankly, I don't see a considerable number of people potentially wanting this to be done. So, if we were to ask you to develop it for our website, how much will it cost?

**Comment by timhunt** [comment]
I don't do commercial development. I work for the Open University, and develop the features they want. I don't have time for anything else. (But, there are Moodle partners who offer commercial development services.)

**Comment by joyhaddad0** [comment]
Oh, alright then, cheers 😃

**Comment by nadavkav** [comment]
We are also experiencing this

**Comment by timhunt** [comment]
I still think that the solution is to add a new Admin setting on .../admin/settings.php?section=filtersettingembedquestion. Something like "Other secrets allowed to validate embedding". That could be a text box with one string per line.

And, that page could also be made to show the secret this site is using - so it can be copied and pasted to other servers.

Then you need to change the code in classes/token.php and the other bits of code that use that to verify tokens, so that if the main secret does not work, it tries all the allowed alternatives before telling the user what they are doing is not allowed.

However, this is still something the OU does not need ourselves, so if you really want this, you will have to code it and send a pull request.

**Comment by timhunt** [comment]
I just merged pull #17, which adds an admin setting where you can input alternate secrets, so I think that effectively solves this issue. Closing.
