### ISSUE TITLE
Toggle to allow embedding questions/categories without an ID number

### ISSUE THREAD

**Issue by ghost** [moodleou/moodle-filter_embedquestion#14]
Can a global toggle be implemented to allow embedding of questions/categories without ID numbers? We don't advise end users to set an ID number when they create questions and don't feel that embedding exam questions is a risk.

**Comment by aspark21** [comment]
Hi Tim,

Surely from a technical point of view this could be amended to enabled the use of the question id and category id rather than relying on a user defined user ID?

My understanding is that at the OU you have the whole XML content authoring approach which means you can be confident those ID numbers will be generated an unique but just about any other institution won't and it makes for a pretty painful experience as a content author to have to go through fiddling with ID numbers manually & coming up with an institutional policy on how to number them uniquely without clashing with other questions in other courses.

So having a site admin setting to either use ID numbers or question/category ids would seem helpful to allow broader adoption outside the OU.

I acknowledge it's probably quite a bit of work but we could potentially look at getting a developer of our own to look at that in 2021 to look into it. Assuming you are comfortable with the approach.

Thanks
Alistair

**Comment by timhunt** [comment]
Have you looked at the code. This is a fundamental assumption built in to how it works. And - the main reason for doing it this was was backup and restore. There is no way that filters could update embed codes based on questionid, so if you backed up and restored a course, then all the ebedded questions would break. We did not want that.

What we did do, because of this feature, was the enhancement MDL-66553 in Moodle 3.8, so that idnumber can clearly be seen in the question bank.

Anyway, we do not intend to change this aspect of how this plugin works. You are welcome to use this, but you don't have to if it does not work for you.
