### ISSUE TITLE
Not working with moodle 3.6

### ISSUE THREAD

**Issue by rezeau** [moodleou/moodle-filter_embedquestion#4]
Using version 1.4 for Moodle 3.4+ (2018111900)Moodle 3.4, 3.5, 3.6
That worked OK with moodle 3.5.3. Just upgraded to moodle 3.6.1 and it does not work. I do get the Embed question icon on the ATTO toolbar, I do have questions with an IDNUMBER in my questions bank, but the categories list is empty.

**Comment by timhunt** [comment]
Note that, although Moodle 3.6 has proper idnumber fields for questions and categories - and we added that to standard Moodle to help this pluging work. Actually, we ahve not yet made teh change so that this plugin uses the idnumber field. You still have to put [ID:someid] in the category/question name.

We really must find time to change this plugin to use the real idnumbers, but I don't know when that will be.

**Comment by rezeau** [comment]
Thanks for your reply, Tim. I thought so. I had tried with the previous method, but had forgotten that you must put an ID in the category name (as well as in the question names).

**Comment by austin-powell** [comment]
From what I'm seeing in Moodle 3.6.2+ and plugin version 2018111900, this issue still has not been fixed. Is this correct? 
If so, is there any estimated timeline for the plugin to work as expected?
Alternatively, is there a place in the code you can point our developers to look at to try to implement this behavior ourselves?
